package org.bytedeco.pytorch.data.avro;
import org.bytedeco.pytorch.nn.options.*;

import org.apache.avro.Schema;
import org.apache.avro.file.CodecFactory;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericDatumWriter;
import org.apache.avro.generic.GenericRecord;
import org.bytedeco.pytorch.data.dataframe.Column;
import org.bytedeco.pytorch.data.dataframe.DataFrame;

import java.io.File;
import java.nio.ByteBuffer;
import java.nio.file.Path;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;

/**
 * Write a {@link DataFrame} as an Avro data file (nullable unions by default).
 */
public final class LocalAvroWriter {
    private LocalAvroWriter() {}

    public static void write(DataFrame df, String path) throws Exception {
        write(df, path, AvroOptions.defaults());
    }

    public static void write(DataFrame df, String path, AvroOptions options) throws Exception {
        AvroOptions opt = options == null ? AvroOptions.defaults() : options;
        Schema schema = buildSchema(df, opt);
        File file = Path.of(path).toFile();
        try (DataFileWriter<GenericRecord> writer =
                 new DataFileWriter<>(new GenericDatumWriter<>(schema))) {
            switch (opt.codec()) {
                case DEFLATE:
                    writer.setCodec(CodecFactory.deflateCodec(opt.deflateLevel()));
                    break;
                case SNAPPY:
                    try {
                        writer.setCodec(CodecFactory.snappyCodec());
                    } catch (Exception ex) {
                        writer.setCodec(CodecFactory.deflateCodec(opt.deflateLevel()));
                    }
                    break;
                case NULL:
                default:
                    writer.setCodec(CodecFactory.nullCodec());
                    break;
            }
            writer.create(schema, file);
            for (int r = 0; r < df.rowCount(); r++) {
                GenericRecord rec = new GenericData.Record(schema);
                for (int c = 0; c < df.columnCount(); c++) {
                    Column col = df.column(c);
                    rec.put(c, toAvroValue(col.get(r), col.dtype()));
                }
                writer.append(rec);
            }
        }
    }

    static Schema buildSchema(DataFrame df, AvroOptions opt) {
        List<Schema.Field> fields = new ArrayList<>();
        for (int i = 0; i < df.columnCount(); i++) {
            Column col = df.column(i);
            Column.DType dt = col.dtype();
            if (opt.schema() != null && opt.schema().containsKey(col.name())) {
                dt = opt.schema().get(col.name());
            }
            Schema fieldSchema = dtypeToAvro(dt);
            if (opt.nullableFields()) {
                fieldSchema = Schema.createUnion(List.of(Schema.create(Schema.Type.NULL), fieldSchema));
            }
            fields.add(new Schema.Field(col.name(), fieldSchema, null,
                opt.nullableFields() ? Schema.Field.NULL_DEFAULT_VALUE : (Object) null));
        }
        Schema record = Schema.createRecord("DataFrame", "generated by bytedeco DataFrame",
            "org.bytedeco.pytorch.data", false);
        record.setFields(fields);
        return record;
    }

    static Schema dtypeToAvro(Column.DType dt) {
        switch (dt) {
            case BOOLEAN: return Schema.create(Schema.Type.BOOLEAN);
            case INT32: return Schema.create(Schema.Type.INT);
            case INT64: return Schema.create(Schema.Type.LONG);
            case FLOAT32: return Schema.create(Schema.Type.FLOAT);
            case FLOAT64: return Schema.create(Schema.Type.DOUBLE);
            case BINARY: return Schema.create(Schema.Type.BYTES);
            case DATE: {
                Schema s = Schema.create(Schema.Type.INT);
                // logicalType annotation as prop for broader compatibility
                s.addProp("logicalType", "date");
                return s;
            }
            case DATETIME: {
                Schema s = Schema.create(Schema.Type.LONG);
                s.addProp("logicalType", "timestamp-millis");
                return s;
            }
            default:
                return Schema.create(Schema.Type.STRING);
        }
    }

    static Object toAvroValue(Object val, Column.DType dtype) {
        if (val == null) return null;
        switch (dtype) {
            case INT32:
                return val instanceof Number ? ((Number) val).intValue()
                    : Integer.parseInt(String.valueOf(val));
            case INT64:
                return val instanceof Number ? ((Number) val).longValue()
                    : Long.parseLong(String.valueOf(val));
            case FLOAT32:
                return val instanceof Number ? ((Number) val).floatValue()
                    : Float.parseFloat(String.valueOf(val));
            case FLOAT64:
                return val instanceof Number ? ((Number) val).doubleValue()
                    : Double.parseDouble(String.valueOf(val));
            case BOOLEAN:
                return val instanceof Boolean ? val : Boolean.parseBoolean(String.valueOf(val));
            case DATE:
                if (val instanceof LocalDate) return (int) ((LocalDate) val).toEpochDay();
                if (val instanceof Number) return ((Number) val).intValue();
                return (int) LocalDate.parse(String.valueOf(val)).toEpochDay();
            case DATETIME:
                if (val instanceof LocalDateTime) {
                    return ((LocalDateTime) val).toInstant(ZoneOffset.UTC).toEpochMilli();
                }
                if (val instanceof Instant) return ((Instant) val).toEpochMilli();
                if (val instanceof Number) return ((Number) val).longValue();
                return Instant.parse(String.valueOf(val)).toEpochMilli();
            case BINARY:
                if (val instanceof byte[]) return ByteBuffer.wrap((byte[]) val);
                return ByteBuffer.wrap(String.valueOf(val).getBytes(java.nio.charset.StandardCharsets.UTF_8));
            default:
                return String.valueOf(val);
        }
    }
}
