package org.bytedeco.pytorch.data.avro;
import org.bytedeco.pytorch.nn.options.*;

import org.apache.avro.Schema;
import org.apache.avro.file.CodecFactory;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericDatumWriter;
import org.apache.avro.generic.GenericRecord;
import org.bytedeco.pytorch.data.dataframe.Column;
import org.bytedeco.pytorch.data.dataframe.DataFrame;
import org.bytedeco.pytorch.data.dataframe.io.ComplexCellCodec;

import java.io.File;
import java.nio.ByteBuffer;
import java.nio.file.Path;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Write a {@link DataFrame} as an Avro data file (nullable unions by default).
 */
public final class LocalAvroWriter {
    private LocalAvroWriter() {}

    public static void write(DataFrame df, String path) throws Exception {
        write(df, path, AvroOptions.defaults());
    }

    public static void write(DataFrame df, String path, AvroOptions options) throws Exception {
        AvroOptions opt = options == null ? AvroOptions.defaults() : options;
        Schema schema = buildSchema(df, opt);
        File file = Path.of(path).toFile();
        try (DataFileWriter<GenericRecord> writer =
                 new DataFileWriter<>(new GenericDatumWriter<>(schema))) {
            switch (opt.codec()) {
                case DEFLATE:
                    writer.setCodec(CodecFactory.deflateCodec(opt.deflateLevel()));
                    break;
                case SNAPPY:
                    try {
                        writer.setCodec(CodecFactory.snappyCodec());
                    } catch (Exception ex) {
                        writer.setCodec(CodecFactory.deflateCodec(opt.deflateLevel()));
                    }
                    break;
                case NULL:
                default:
                    writer.setCodec(CodecFactory.nullCodec());
                    break;
            }
            writer.create(schema, file);
            for (int r = 0; r < df.rowCount(); r++) {
                GenericRecord rec = new GenericData.Record(schema);
                for (int c = 0; c < df.columnCount(); c++) {
                    Column col = df.column(c);
                    rec.put(c, toAvroValue(col.get(r), col.dtype()));
                }
                writer.append(rec);
            }
        }
    }

    static Schema buildSchema(DataFrame df, AvroOptions opt) {
        List<Schema.Field> fields = new ArrayList<>();
        for (int i = 0; i < df.columnCount(); i++) {
            Column col = df.column(i);
            Column.DType dt = col.dtype();
            if (opt.schema() != null && opt.schema().containsKey(col.name())) {
                dt = opt.schema().get(col.name());
            }
            Schema fieldSchema = dtypeToAvro(dt);
            if (opt.nullableFields()) {
                fieldSchema = Schema.createUnion(List.of(Schema.create(Schema.Type.NULL), fieldSchema));
            }
            fields.add(new Schema.Field(col.name(), fieldSchema, null,
                opt.nullableFields() ? Schema.Field.NULL_DEFAULT_VALUE : (Object) null));
        }
        Schema record = Schema.createRecord("DataFrame", "generated by bytedeco DataFrame",
            "org.bytedeco.pytorch.data", false);
        record.setFields(fields);
        return record;
    }

    static Schema dtypeToAvro(Column.DType dt) {
        switch (dt) {
            case BOOLEAN: return Schema.create(Schema.Type.BOOLEAN);
            case INT32: return Schema.create(Schema.Type.INT);
            case INT64: return Schema.create(Schema.Type.LONG);
            case FLOAT32: return Schema.create(Schema.Type.FLOAT);
            case FLOAT64: return Schema.create(Schema.Type.DOUBLE);
            case BINARY: return Schema.create(Schema.Type.BYTES);
            case DATE: {
                Schema s = Schema.create(Schema.Type.INT);
                // logicalType annotation as prop for broader compatibility
                s.addProp("logicalType", "date");
                return s;
            }
            case DATETIME: {
                Schema s = Schema.create(Schema.Type.LONG);
                s.addProp("logicalType", "timestamp-millis");
                return s;
            }
            case VECTOR:
            case EMBEDDING:
                // dense float vectors as array<float>
                return Schema.createArray(Schema.create(Schema.Type.FLOAT));
            case LIST:
                // heterogeneous / item sequences: array of JSON-encoded strings is too lossy;
                // use array of long by default (item ids); wider types go through union below
                // Prefer array<string> for general lists — values are JSON-text of element when nested
                // Better: array of nullable union of primitives + string for nested
                return Schema.createArray(Schema.createUnion(List.of(
                    Schema.create(Schema.Type.NULL),
                    Schema.create(Schema.Type.LONG),
                    Schema.create(Schema.Type.DOUBLE),
                    Schema.create(Schema.Type.STRING),
                    Schema.create(Schema.Type.BOOLEAN)
                )));
            case MAP:
            case STRUCT:
                // map<string, string> with JSON-encoded nested values for portability
                // Prefer map of nullable string (JSON text of value)
                return Schema.createMap(Schema.createUnion(List.of(
                    Schema.create(Schema.Type.NULL),
                    Schema.create(Schema.Type.STRING),
                    Schema.create(Schema.Type.LONG),
                    Schema.create(Schema.Type.DOUBLE),
                    Schema.create(Schema.Type.BOOLEAN)
                )));
            case JSON:
                return Schema.create(Schema.Type.STRING);
            default:
                return Schema.create(Schema.Type.STRING);
        }
    }

    static Object toAvroValue(Object val, Column.DType dtype) {
        if (val == null) return null;
        switch (dtype) {
            case INT32:
                return val instanceof Number ? ((Number) val).intValue()
                    : Integer.parseInt(String.valueOf(val));
            case INT64:
                return val instanceof Number ? ((Number) val).longValue()
                    : Long.parseLong(String.valueOf(val));
            case FLOAT32:
                return val instanceof Number ? ((Number) val).floatValue()
                    : Float.parseFloat(String.valueOf(val));
            case FLOAT64:
                return val instanceof Number ? ((Number) val).doubleValue()
                    : Double.parseDouble(String.valueOf(val));
            case BOOLEAN:
                return val instanceof Boolean ? val : Boolean.parseBoolean(String.valueOf(val));
            case DATE:
                if (val instanceof LocalDate) return (int) ((LocalDate) val).toEpochDay();
                if (val instanceof Number) return ((Number) val).intValue();
                return (int) LocalDate.parse(String.valueOf(val)).toEpochDay();
            case DATETIME:
                if (val instanceof LocalDateTime) {
                    return ((LocalDateTime) val).toInstant(ZoneOffset.UTC).toEpochMilli();
                }
                if (val instanceof Instant) return ((Instant) val).toEpochMilli();
                if (val instanceof Number) return ((Number) val).longValue();
                return Instant.parse(String.valueOf(val)).toEpochMilli();
            case BINARY:
                if (val instanceof byte[]) return ByteBuffer.wrap((byte[]) val);
                return ByteBuffer.wrap(String.valueOf(val).getBytes(java.nio.charset.StandardCharsets.UTF_8));
            case VECTOR:
            case EMBEDDING: {
                List<Object> elems = ComplexCellCodec.asObjectList(val);
                if (elems == null) return null;
                List<Float> out = new ArrayList<>(elems.size());
                for (Object o : elems) {
                    if (o == null) out.add(Float.NaN);
                    else if (o instanceof Number) out.add(((Number) o).floatValue());
                    else out.add(Float.parseFloat(String.valueOf(o)));
                }
                return out;
            }
            case LIST: {
                List<Object> elems = ComplexCellCodec.asObjectList(val);
                if (elems == null) return null;
                List<Object> out = new ArrayList<>(elems.size());
                for (Object o : elems) {
                    out.add(toAvroListElement(o));
                }
                return out;
            }
            case MAP:
            case STRUCT: {
                Map<String, Object> m = ComplexCellCodec.asStringMap(val);
                if (m == null) return null;
                Map<String, Object> out = new LinkedHashMap<>();
                for (Map.Entry<String, Object> e : m.entrySet()) {
                    out.put(e.getKey(), toAvroMapValue(e.getValue()));
                }
                return out;
            }
            case JSON:
                return ComplexCellCodec.encodeText(val);
            default:
                // TENSOR / GRAPH / media etc. → JSON text for portability
                if (ComplexCellCodec.isComplex(dtype)
                    || val instanceof Map || val instanceof List
                    || val instanceof float[] || val instanceof double[]
                    || val instanceof int[] || val instanceof long[]) {
                    return ComplexCellCodec.encodeText(val);
                }
                return String.valueOf(val);
        }
    }

    /** Encode a LIST element into the Avro union (null/long/double/string/boolean). */
    private static Object toAvroListElement(Object o) {
        if (o == null) return null;
        if (o instanceof Boolean) return o;
        if (o instanceof Integer || o instanceof Long || o instanceof Short || o instanceof Byte) {
            return ((Number) o).longValue();
        }
        if (o instanceof Float || o instanceof Double) {
            return ((Number) o).doubleValue();
        }
        if (o instanceof Number) return ((Number) o).longValue();
        // nested list/map/array → JSON string
        if (o instanceof Map || o instanceof List || o.getClass().isArray()) {
            return ComplexCellCodec.encodeText(o);
        }
        return String.valueOf(o);
    }

    /** Encode a MAP/STRUCT value into the Avro map value union. */
    private static Object toAvroMapValue(Object o) {
        if (o == null) return null;
        if (o instanceof Boolean) return o;
        if (o instanceof Integer || o instanceof Long || o instanceof Short || o instanceof Byte) {
            return ((Number) o).longValue();
        }
        if (o instanceof Float || o instanceof Double) {
            return ((Number) o).doubleValue();
        }
        if (o instanceof Number) return ((Number) o).doubleValue();
        if (o instanceof Map || o instanceof List || o.getClass().isArray()) {
            return ComplexCellCodec.encodeText(o);
        }
        return String.valueOf(o);
    }
}

