//// Targeted by JavaCPP version 1.5.14-SNAPSHOT: DO NOT EDIT THIS FILE
//
//package org.bytedeco.pytorch.global;
//import org.bytedeco.pytorch.jit.*;
//
//import org.bytedeco.pytorch.onnx.*;
//
//import java.nio.*;
//import org.bytedeco.javacpp.*;
//import org.bytedeco.javacpp.annotation.*;
//
//import static org.bytedeco.javacpp.presets.javacpp.*;
//import static org.bytedeco.openblas.global.openblas_nolapack.*;
//import static org.bytedeco.openblas.global.openblas.*;
//import org.bytedeco.javacpp.chrono.*;
//import static org.bytedeco.javacpp.global.chrono.*;
//import org.bytedeco.pytorch.*;
//import org.bytedeco.pytorch.nn.*;
//import org.bytedeco.pytorch.nn.modules.*;
//import org.bytedeco.pytorch.nn.modules.container.*;
//import org.bytedeco.pytorch.nn.options.*;
//import static org.bytedeco.pytorch.global.torch.*;
//
//public class torch_onnx extends org.bytedeco.pytorch.presets.torch_onnx {
//    static { Loader.load(); }
///**
// * Load a serialized TorchScript {@code JitModule} from {@code filename}.
// * Equivalent to {@code torch.jit.load} / {@code org.bytedeco.pytorch.global.torch.load}.
// * For raw {@code .onnx} protobuf inference, use {@code org.bytedeco.onnxruntime}.
// */
//public static org.bytedeco.pytorch.jit.JitModule loadModule(String filename) {
//    return org.bytedeco.pytorch.global.torch.load(filename);
//}
//
///**
// * Load a TorchScript module onto {@code device}.
// */
//public static org.bytedeco.pytorch.jit.JitModule loadModule(String filename,
//        org.bytedeco.pytorch.DeviceOptional device) {
//    return org.bytedeco.pytorch.global.torch.load(filename, device, true);
//}
//
///**
// * Export {@code module} to {@code filename} via {@code torch::jit::ExportModule}.
// * Prefer this free function when you need bytecode/flatbuffer flags;
// * otherwise {@code module.save(filename)} is equivalent for the default path.
// */
//public static void exportModule(org.bytedeco.pytorch.jit.JitModule module, String filename) {
//    ExportModule(module, filename);
//}
//
///**
// * Export {@code module} with explicit format flags.
// */
//public static void exportModule(org.bytedeco.pytorch.jit.JitModule module, String filename,
//        boolean bytecode_format, boolean save_mobile_debug_info, boolean use_flatbuffer) {
//    ExportModule(module, filename,
//        new org.bytedeco.pytorch.ExtraFilesMap(),
//        bytecode_format, save_mobile_debug_info, use_flatbuffer);
//}
//
//
//// Parsed from torch/csrc/onnx/onnx.h
//
//// #if !defined(TORCH_STABLE_ONLY) && !defined(TORCH_TARGET_VERSION)
//// #pragma once
//
//@Namespace("torch::onnx") public enum OperatorExportTypes {
//  ONNX(0), // Strict ONNX export
//  ONNX_ATEN(1), // ONNX With ATen op everywhere
//  ONNX_ATEN_FALLBACK(2), // ONNX export with ATen fallback
//  ONNX_FALLTHROUGH(3);// Export supported ONNX ops. Pass through unsupported ops.
//
//    public final int value;
//    private OperatorExportTypes(int v) { this.value = v; }
//    private OperatorExportTypes(OperatorExportTypes e) { this.value = e.value; }
//    public OperatorExportTypes intern() { for (OperatorExportTypes e : values()) if (e.value == value) return e; return this; }
//    @Override public String toString() { return intern().name(); }
//}
//
//@Namespace("torch::onnx") public enum TrainingMode {
//  EVAL(0), // Inference mode
//  PRESERVE(1), // Preserve model state (eval/training)
//  TRAINING(2);// Training mode
//
//    public final int value;
//    private TrainingMode(int v) { this.value = v; }
//    private TrainingMode(TrainingMode e) { this.value = e.value; }
//    public TrainingMode intern() { for (TrainingMode e : values()) if (e.value == value) return e; return this; }
//    @Override public String toString() { return intern().name(); }
//}
//
///** Attribute name used for ONNX node names (torch::onnx::kOnnxNodeNameAttribute). */
//public static final String kOnnxNodeNameAttribute = "onnx_name";
//
// // namespace torch::onnx
//
//// #else
//// #error "This file should not be included when either TORCH_STABLE_ONLY or TORCH_TARGET_VERSION is defined."
//// #endif  // !defined(TORCH_STABLE_ONLY) && !defined(TORCH_TARGET_VERSION)
//
//
//// Parsed from export_module_java.h
//
///*
// * Parse-time / JNI shim for bindable torch::jit::ExportModule surface and
// * torch::jit::ToONNX (Graph→ONNX Graph) without walking ModelProto / pybind.
// *
// * Real headers:
// *   torch/csrc/jit/serialization/export.h  — ExportModule, export_opnames
// *   torch/csrc/jit/passes/onnx.h           — ToONNX (plus pybind overloads)
// *
// * At JNI compile time, torch_onnx.init() may swap this shim for the real
// * export.h if desired; symbols live in libtorch_cpu (ExportModule) and
// * libtorch_python (ToONNX).
// */
//// #pragma once
//
//// #include <torch/csrc/jit/api/module.h>
//// #include <torch/csrc/jit/ir/ir.h>
//// #include <torch/csrc/onnx/onnx.h>
//
//// #include <ostream>
//// #include <string>
//// #include <vector>
//// #include <memory>
//
//@Namespace("torch::jit") public static native void ExportModule(
//    @Const @ByRef JitModule module,
//    @Cast("std::ostream*") @ByRef Pointer out,
//    @Const @ByRef(nullValue = "ExtraFilesMap()") ExtraFilesMap metadata,
//    @Cast("bool") boolean bytecode_format/*=false*/,
//    @Cast("bool") boolean save_mobile_debug_info/*=false*/,
//    @Cast("bool") boolean use_flatbuffer/*=false*/);
//@Namespace("torch::jit") public static native void ExportModule(
//    @Const @ByRef JitModule module,
//    @Cast("std::ostream*") @ByRef Pointer out);
//
//@Namespace("torch::jit") public static native void ExportModule(
//    @Const @ByRef JitModule module,
//    @StdString BytePointer filename,
//    @Const @ByRef(nullValue = "ExtraFilesMap()") ExtraFilesMap metadata,
//    @Cast("bool") boolean bytecode_format/*=false*/,
//    @Cast("bool") boolean save_mobile_debug_info/*=false*/,
//    @Cast("bool") boolean use_flatbuffer/*=false*/);
//@Namespace("torch::jit") public static native void ExportModule(
//    @Const @ByRef JitModule module,
//    @StdString BytePointer filename);
//@Namespace("torch::jit") public static native void ExportModule(
//    @Const @ByRef JitModule module,
//    @StdString String filename,
//    @Const @ByRef(nullValue = "ExtraFilesMap()") ExtraFilesMap metadata,
//    @Cast("bool") boolean bytecode_format/*=false*/,
//    @Cast("bool") boolean save_mobile_debug_info/*=false*/,
//    @Cast("bool") boolean use_flatbuffer/*=false*/);
//@Namespace("torch::jit") public static native void ExportModule(
//    @Const @ByRef JitModule module,
//    @StdString String filename);
//
//@Namespace("torch::jit") public static native @ByVal StringVector export_opnames(@Const @ByRef JitModule m);
//
//// Graph → ONNX Graph conversion (no protobuf). Full signature from passes/onnx.h.
//@Namespace("torch::jit") public static native @SharedPtr Graph ToONNX(
//    @SharedPtr Graph state,
//    OperatorExportTypes operator_export_type);
//
//@Namespace("torch::jit") public static native void RemovePrintOps(@SharedPtr Graph graph);
//@Namespace("torch::jit") public static native void PreprocessCaffe2Ops(@SharedPtr Graph graph);
//
// // namespace torch::jit
//
//
//}
