name: cuda
on:
  push:
    paths:
      - cuda/**
      - .github/workflows/cuda.yml
  pull_request:
    paths:
      - cuda/**
      - .github/workflows/cuda.yml
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-arm64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        file: [redist, redist-cublas, redist-cudnn, redist-cusolver, redist-cusparse, redist-npp, redist-nccl, redist-nvcomp]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  linux-ppc64le:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        file: [redist, redist-cublas, redist-cudnn, redist-cusolver, redist-cusparse, redist-npp, redist-nccl, redist-nvcomp]
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-x86_64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        file: [redist, redist-cublas, redist-cudnn, redist-cusolver, redist-cusparse, redist-npp, redist-nccl, redist-nvcomp]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  macosx-x86_64:
#    runs-on: macos-13
#    strategy:
#      matrix:
#        file: [redist, redist-cublas, redist-cudnn, redist-cusolver, redist-cusparse, redist-npp, redist-nccl, redist-nvcomp]
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86_64:
    runs-on: windows-2022
    strategy:
      matrix:
        file: [redist, redist-cublas, redist-cudnn, redist-cusolver, redist-cusparse, redist-npp, redist-nccl, redist-nvcomp]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  platform:
    needs: [linux-arm64, linux-x86_64, windows-x86_64]
#    needs: [linux-ppc64le, linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        file: [redist, redist-cublas, redist-cudnn, redist-cusolver, redist-cusparse, redist-npp, redist-nccl, redist-nvcomp]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
