name: depthai
on:
  push:
    paths:
      - depthai/**
      - .github/workflows/depthai.yml
  pull_request:
    paths:
      - depthai/**
      - .github/workflows/depthai.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-armhf:
    runs-on: ubuntu-20.04
    container: ubuntu:bionic
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-arm64:
    runs-on: ubuntu-20.04
    container: ubuntu:bionic
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-x86:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86_64:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-11
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86:
    runs-on: windows-2019
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
    needs: [linux-armhf, linux-arm64, linux-x86, linux-x86_64, macosx-x86_64, windows-x86, windows-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
