name: ffmpeg
on:
  push:
    paths:
      - ffmpeg/**
  pull_request:
    paths:
      - ffmpeg/**
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  android-arm:
    runs-on: ubuntu-16.04
    container: centos:7
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-arm64:
    runs-on: ubuntu-16.04
    container: centos:7
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-x86:
    runs-on: ubuntu-16.04
    container: centos:7
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-x86_64:
    runs-on: ubuntu-16.04
    container: centos:7
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-armhf:
    runs-on: ubuntu-16.04
    container: ubuntu:xenial
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-arm64:
    runs-on: ubuntu-16.04
    container: ubuntu:xenial
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-ppc64le:
    runs-on: ubuntu-16.04
    container: ubuntu:xenial
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-x86:
    runs-on: ubuntu-16.04
    container: centos:6
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86_64:
    runs-on: ubuntu-16.04
    container: centos:6
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-10.15
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  windows-x86_64:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
    needs: [android-arm, android-arm64, android-x86, android-x86_64, linux-armhf, linux-arm64, linux-ppc64le, linux-x86, linux-x86_64, macosx-x86_64, windows-x86, windows-x86_64]
    runs-on: ubuntu-16.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
