name: mxnet
on:
  push:
    paths:
      - mxnet/**
  pull_request:
    paths:
      - mxnet/**
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86:
    runs-on: ubuntu-16.04
    container: centos:6
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86_64:
    runs-on: ubuntu-16.04
    container: centos:6
    strategy:
      fail-fast: false
      matrix:
        ext: ["", -gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-10.15
#    strategy:
#      fail-fast: false
#      matrix:
#        ext: ["", -gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86_64:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ext: ["", -gpu]
    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
    needs: [linux-x86, linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-16.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
