name: shaka-packager
on:
  push:
    paths:
      - shaka-packager/**
      - .github/workflows/shaka-packager.yml
  pull_request:
    paths:
      - shaka-packager/**
      - .github/workflows/shaka-packager.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE_NINJA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/deploy-ubuntu@shaka-packager
  linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/deploy-ubuntu@shaka-packager
  macosx-arm64:
    runs-on: macos-12
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/deploy-macosx@shaka-packager
  macosx-x86_64:
    runs-on: macos-12
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/deploy-macosx@shaka-packager
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/deploy-windows@shaka-packager
  redeploy:
    needs: [linux-arm64, linux-x86_64, macosx-x86_64, macosx-arm64, windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/redeploy@shaka-packager
