name: shaka-packager
on:
  push:
    paths:
      - shaka-packager/**
      - .github/workflows/shaka-packager.yml
  pull_request:
    paths:
      - shaka-packager/**
      - .github/workflows/shaka-packager.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE_NINJA: 0
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  windows-x86_64:
    runs-on: windows-2022
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/deploy-windows@shaka-packager
  redeploy:
    needs: [windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: zaki699/javacpp-presets/.github/actions/redeploy@shaka-packager
