name: skia
on:
  push:
    paths:
      - skia/**
  pull_request:
    paths:
      - skia/**
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  ios-arm64:
    runs-on: macos-10.15
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  ios-x86_64:
    runs-on: macos-10.15
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  linux-x86:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86_64:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-10.15
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  redeploy:
    needs: [ios-arm64, ios-x86_64, linux-x86, linux-x86_64, macosx-x86_64]
    runs-on: ubuntu-18.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
